#!/usr/bin/env bash
# This script provides answers to MAC and IP address questions

# Question 1
echo "What is a MAC address?"
echo "1. The name of a network interface"
echo "2. The unique identifier of a network interface"
echo "3. A network interface"

# Correct answer to question 1
echo "Correct Answer: 2"

# Question 2
echo ""
echo "What is an IP address?"
echo "1. Is to devices connected to a network what postal address is to houses"
echo "2. The unique identifier of a network interface"
echo "3. Is a number that network devices use to connect to networks"

# Correct answer to question 2
echo "Correct Answer: 1"

