#!/bin/bash

# Display listening ports with PID and program name
sudo netstat -tulpen | grep 'LISTEN'
sudo netstat -tulpen | grep 'LISTEN' | awk '{print $9}' | sed 's,.*:,,;s,.*,/,' | xargs -r ps -p

