#!/usr/bin/env bash
# 101-manage_my_process init script

# Function to start the manage_my_process script
start() {
  if [ -f "/var/run/my_process.pid" ]; then
    echo "manage_my_process is already running."
  else
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
  fi
}

# Function to stop the manage_my_process script
stop() {
  if [ -f "/var/run/my_process.pid" ]; then
    pid=$(cat "/var/run/my_process.pid")
    kill "$pid"
    rm "/var/run/my_process.pid"
    echo "manage_my_process stopped"
  else
    echo "manage_my_process is not running."
  fi
}

# Function to restart the manage_my_process script
restart() {
  stop
  start
  echo "manage_my_process restarted"
}

# Main script
case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac


