#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
to_infinity_pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process is running
if [ -n "$to_infinity_pid" ]; then
  # Use kill to terminate the process
  kill "$to_infinity_pid"
  echo "Terminated"
else
  echo "Process not found"
fi

