#!/usr/bin/env bash
# This script tells the story of /etc/passwd using the while loop + IFS.

# Read each line from /etc/passwd
while IFS=: read -r username _ uid gid info home_path shell; do
    # Display the story based on the extracted information
    echo "The user $username is part of the $gid gang, lives in $home_path and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $info"
done < /etc/passwd

